services:
  db:
    image: mysql:8.0
    container_name: esempio-db
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: segreta
      MYSQL_DATABASE: esempio
      MYSQL_USER: db_admin
      MYSQL_PASSWORD: admin_user_password
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-psegreta"]
      interval: 5s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8089:80"



  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: esempio-flask
    environment:
      DB_HOST: db
      DB_USER: db_admin
      DB_PASSWORD: admin_user_password
      DB_NAME: esempio
    volumes:
      - uploads:/app/uploads
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: esempio-nginx
    ports:
      - "8085:80"
    depends_on:
      - backend

volumes:
  uploads:
  mysql-data:
    external: true